URL_NAMES = {
    'tohno': 'Shiki_Tohno',
    'arcueid': 'Arcueid_Brunestud',
    'akiha': 'Akiha_Tohno',
    'ciel': 'Ciel',
    'hisui': 'Hisui',
    'kohaku': 'Kohaku',
    'maids': 'Hisui_&_Kohaku',
    'miyako': 'Miyako_Arima',
    'kouma': 'Kouma_Kishima',
    'noel': 'Noel',
    'roa': 'Michael_Roa_Valdamjong',
    'vlov': 'Vlov_Arkhangel',
    'warc': 'Red_Arcueid',
    'saber': 'Saber',
    'aoko': 'Aoko_Aozaki',
    'dan': 'Dead_Apostle_Noel',
    'mario': 'Mario_Gallo_Bestino',
    'pciel': 'Powered_Ciel',
    'neco': 'Neco-Arc',
    'mash': 'Mash_Kyrielight',
    'ushi': 'Ushiwakamaru',
    'dantes': 'Monte_Cristo'
}